### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by vovayatsyuk** [swissup/module-marketplace#1]
### Code

- [x] Remote packages cache
- [x] Channel switcher
- [x] Pagination
- [x] Auth credentials check
- [x] Auth key ui component
- [x] Get local versions from composer.lock (This will work with metapackages.)
- [x] Public URL for channel to get latest versions (To show that there are updates that are not available)
- [x] Queue and cron-based jobs to manage modules
- [x] ~~Package details modal with recent logs and dependencies~~ (Add in the next release)
- [x] ~~Move swissup channel to separate module~~ (Next releases.)
- [x] Floating jobs or button (counter) with modal with a grid of pending and processed jobs
- [x] CLI commands
- [x] Readme file
- [x] Installer
- [x] Uninstall theme (unset config, remove virtual theme)
- [x] Memory limit
- [x] Reset grid cache after “update row data”
- [ ] Test in production mode
- [ ] Test `@extends` directive
- [x] Don’t show popup when installer is not available
- [x] CLI doesn’t work on Mac (strpad?)

### Swissup

- [x] Images for all packages
